#!/bin/bash

shopt -s expand_aliases
alias groot="git rev-parse --show-toplevel"
alias gw='$(groot)/gradlew'

function get-module() {
	while read line
	do
		if test -f $line/bnd.bnd; then
			echo "$line";
		elif [ "$line" != "." ]; then
			(dirname $line | get-module)
		fi
	done
}

function run-stdin() {
	while read line
	do
		echo "" | (cd $(groot)/$line; $*)
	done
}

function liferay-get-modules() {
	(cd $(groot) && $* --name-only | get-module | uniq)
}

function liferay-changed-modules() {
	liferay-get-modules git diff --name-only ${BRANCH:-master}
}

liferay-changed-modules | grep -v test | run-stdin gw -a deploy